"""JSON backup / restore for user-entered data.

Exports everything the user has manually entered (bills, BNPL, envelopes,
goals, debts, sync state including manual balance) to a portable JSON dict.
Imports it back.

Excluded from backup (intentional):
  - Account (Plaid-synced — recreated by Sync)
  - Transaction (Plaid-synced — recreated by Sync)
  - transactions_sync_cursor (Plaid-specific, re-derived)
  - Paycheck (regenerated by the calendar service)
"""
from __future__ import annotations

import json
from datetime import date, datetime
from typing import Any, Dict, List

from sqlmodel import Session, select

from models.schema import (
    RecurringBill, BNPLPlan, BNPLInstallment,
    Envelope, SavingsGoal, DebtAccount, SyncState,
)

SCHEMA_VERSION = 1
BACKUP_NAME = "budget-backup.json"


def _row_to_dict(row) -> Dict[str, Any]:
    """Convert a SQLModel row to a JSON-serializable dict."""
    d = row.model_dump()
    for k, v in list(d.items()):
        if isinstance(v, (date, datetime)):
            d[k] = v.isoformat()
    return d


def export_to_dict(session: Session) -> Dict[str, Any]:
    """Read every user-entered table, return one big dict."""
    return {
        "schema_version": SCHEMA_VERSION,
        "exported_at": datetime.utcnow().isoformat(),
        "bills": [_row_to_dict(r) for r in session.exec(select(RecurringBill)).all()],
        "bnpl_plans": [_row_to_dict(r) for r in session.exec(select(BNPLPlan)).all()],
        "bnpl_installments": [_row_to_dict(r) for r in session.exec(select(BNPLInstallment)).all()],
        "envelopes": [_row_to_dict(r) for r in session.exec(select(Envelope)).all()],
        "savings_goals": [_row_to_dict(r) for r in session.exec(select(SavingsGoal)).all()],
        "debt_accounts": [_row_to_dict(r) for r in session.exec(select(DebtAccount)).all()],
        "sync_state": [_row_to_dict(r) for r in session.exec(select(SyncState)).all()
                       if r.key != "transactions_sync_cursor"],
    }


def export_to_json(session: Session, indent: int = 2) -> str:
    """Same as export_to_dict but serialized to a JSON string."""
    return json.dumps(export_to_dict(session), indent=indent, sort_keys=True)


def _parse_dates(d: Dict[str, Any], date_fields: List[str]) -> Dict[str, Any]:
    """Convert ISO date strings back to date objects for the given fields."""
    for f in date_fields:
        v = d.get(f)
        if isinstance(v, str):
            try:
                # Try date-only first, then datetime
                if "T" in v:
                    d[f] = datetime.fromisoformat(v.replace("Z", "+00:00"))
                else:
                    d[f] = date.fromisoformat(v)
            except (ValueError, TypeError):
                d[f] = None
    return d


def _clear_tables(session: Session) -> None:
    """Wipe all user-entered tables before a full restore. Plaid data untouched."""
    for model in (BNPLInstallment, BNPLPlan, RecurringBill,
                  Envelope, SavingsGoal, DebtAccount):
        for row in session.exec(select(model)).all():
            session.delete(row)
    # SyncState: only clear non-Plaid keys
    for row in session.exec(select(SyncState)).all():
        if row.key != "transactions_sync_cursor":
            session.delete(row)
    session.commit()


def import_from_dict(session: Session, data: Dict[str, Any], replace: bool = True) -> Dict[str, int]:
    """Restore from a backup dict.

    replace=True (default): wipe existing user data first, then insert.
    replace=False: insert alongside existing rows (may cause unique-constraint errors).

    Returns {table: count} of inserted rows.
    """
    if not isinstance(data, dict):
        raise ValueError("Backup payload must be a JSON object")
    version = data.get("schema_version")
    if version != SCHEMA_VERSION:
        raise ValueError(
            f"Backup schema_version={version}, expected {SCHEMA_VERSION}. "
            "Different versions may not import cleanly."
        )

    if replace:
        _clear_tables(session)

    counts: Dict[str, int] = {}

    def _insert(name: str, model_cls, rows: List[Dict[str, Any]], date_fields: List[str]):
        n = 0
        for raw in rows or []:
            cleaned = _parse_dates(dict(raw), date_fields)
            cleaned.pop("id", None)  # let DB auto-assign
            try:
                session.add(model_cls(**cleaned))
                n += 1
            except TypeError as e:
                # Schema mismatch on an extra/missing field — skip with note
                raise ValueError(f"Bad {name} row: {e}") from e
        counts[name] = n

    _insert("bills", RecurringBill, data.get("bills", []), ["next_due_date"])
    _insert("envelopes", Envelope, data.get("envelopes", []), [])
    _insert("savings_goals", SavingsGoal, data.get("savings_goals", []), ["target_date"])
    _insert("debt_accounts", DebtAccount, data.get("debt_accounts", []), [])

    # BNPL: insert plans first so installments can reference plan_id.
    # But IDs are auto-assigned — we need to remap plan IDs.
    plan_id_map: Dict[int, int] = {}
    for raw in data.get("bnpl_plans", []) or []:
        cleaned = _parse_dates(dict(raw), ["start_date"])
        old_id = cleaned.pop("id", None)
        plan = BNPLPlan(**cleaned)
        session.add(plan)
        session.flush()  # populate plan.id
        if old_id is not None:
            plan_id_map[old_id] = plan.id
    counts["bnpl_plans"] = len(plan_id_map)

    n_inst = 0
    for raw in data.get("bnpl_installments", []) or []:
        cleaned = _parse_dates(dict(raw), ["due_date"])
        cleaned.pop("id", None)
        old_plan_id = cleaned.get("plan_id")
        new_plan_id = plan_id_map.get(old_plan_id)
        if new_plan_id is None:
            # Orphaned installment — skip
            continue
        cleaned["plan_id"] = new_plan_id
        # paid_transaction_id references Transaction which isn't restored — clear it
        cleaned.pop("paid_transaction_id", None)
        session.add(BNPLInstallment(**cleaned))
        n_inst += 1
    counts["bnpl_installments"] = n_inst

    # SyncState — key is the PK so use raw insert with key
    n_sync = 0
    for raw in data.get("sync_state", []) or []:
        key = raw.get("key")
        value = raw.get("value")
        if not key or key == "transactions_sync_cursor":
            continue
        session.add(SyncState(key=key, value=str(value)))
        n_sync += 1
    counts["sync_state"] = n_sync

    session.commit()
    return counts


def import_from_json(session: Session, json_str: str, replace: bool = True) -> Dict[str, int]:
    """Parse JSON string and call import_from_dict."""
    data = json.loads(json_str)
    return import_from_dict(session, data, replace=replace)
